version: '3.1'

services:

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: hello_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: example
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
#
#  web:
#    build: .
#    container_name: docker-django
#    command: python manage.py runserver 0.0.0.0:8000
#    ports:
#      - "localhost:8000:8000"
#    depends_on:
#      - db