version: '3.1'

services:

#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: hello_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: example
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080